project/routes/routes.py
from flask import Blueprint, render_template, redirect, url_for, abort, request, jsonify, flash
from models.models import SportDB, LeagueDB, TeamsDB, Match_statusDB, MatchesDB
from selenium import webdriver
from sqlalchemy import desc, asc
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.by import By
import time
from datetime import datetime

from extensions import extensions
# from sqlalchemy import desc, asc, func
# from sqlalchemy import and_, or_
# from flask_socketio import SocketIO, emit
# from datetime import datetime

db = extensions.db
# db.create_all()
# db.session.commit()
home = Blueprint('home', __name__, template_folder='templates')

socketio = extensions.socketio

def check_league(driver, country, league_name, sport_id, league_name_el):
    # проверяем есть ли эта лига в базе
    league_data = LeagueDB.query.filter_by(league_country=country, league_name=league_name).first()
    if league_data:
        print("Данные о лиге уже есть в базе. Страна: ", country, ". Лига: ", league_name)
    else:
        # создаем новую лигу
        print("Данных о лиге в нет в базе")
        new_league = LeagueDB(
            league_country=country,
            league_name=league_name,
            sport_id=sport_id
        )
        db.session.add(new_league)
        db.session.commit()
        league_data = LeagueDB.query.order_by(desc(LeagueDB.league_id)).first()
        league_id = league_data.league_id
        print("Лига : ", league_data.league_name, " была создана")
        # переходим в каталог команд
        league_name_el.click()
        driver.implicitly_wait(3)
        driver.find_element("xpath", "//a[@class='tabs__tab standings_table']").click()

        # получаем список команд
        teams = driver.find_elements("xpath", "//a[@class='tableCellParticipant__name']")
        for team in teams:
            team_name = team.text
            # проверяем есть ли уже запись о команде
            team_data = TeamsDB.query.filter_by(league_id=league_id, team_name=team_name).first()
            if team_data:
                pass
            else:
                new_team_record = TeamsDB(
                    league_id=league_id,
                    team_name=team_name
                )
                db.session.add(new_team_record)
                db.session.commit()
                last_created_team = TeamsDB.query.order_by(desc(TeamsDB.team_id)).first()
                print("Команда : ", last_created_team.team_name, " была создана")
        # возвращаемся обратно
        driver.execute_script("window.history.go(-1)")
        driver.implicitly_wait(3)
        driver.execute_script("window.history.go(-1)")
        driver.implicitly_wait(10)
        # print('Enter your name:')
        # x = input()
        tabs = driver.find_elements("xpath", "//div[@class='filters__text filters__text--default']")
        for tab in tabs:
            tab_name = tab.text
            if tab_name.lower() == "завершенные":
                tab.click()




    return league_data

def update_league_and_team_data(driver, country, league_name, sport_id, status):

        # переходим в список команд для заполнения
        driver.find_element("xpath", "//span[@class='event__title--name']").click()
        driver.implicitly_wait(10)
        driver.find_element("xpath", "//a[@class='tabs__tab standings_table']").click()

        # получаем список команд
        teams = driver.find_elements("xpath", "//a[@class='tableCellParticipant__name']")
        for team in teams:
            team_name = team.text
            # проверяем есть ли уже запись о команде
            team_data = TeamsDB.query.filter_by(league_id=league_id, team_name=team_name).first()
            if team_data:
                pass
            else:
                new_team_record = TeamsDB(
                    league_id=league_id,
                    team_name=team_name
                )
                db.session.add(new_team_record)
                db.session.commit()
                last_created_team = TeamsDB.query.order_by(desc(TeamsDB.team_id)).first()
                print("Команда : ", last_created_team.team_name, " была создана")
        # возвращаемся обратно
        driver.execute_script("window.history.go(-1)")
        driver.implicitly_wait(3)
        driver.execute_script("window.history.go(-1)")
        driver.implicitly_wait(10)
        # print('Enter your name:')
        # x = input()
        tabs = driver.find_elements("xpath", "//div[@class='filters__text filters__text--default']")
        for tab in tabs:
            tab_name = tab.text
            if tab_name.lower() == status:
                tab.click()




@home.route('/')
def home_view():
    data = {'active_tab_pass': 'live_matches'}
    # if int(active_tab_name) == 0:
    #     data = {'active_tab_pass': 'live_matches'}
    # if int(active_tab_name) == 1:
    #     data = {'active_tab_pass': 'settings'}

    return render_template('home.html', data=data)

@home.route('/parse_finished')
def parse_finished():
    driver = webdriver.Chrome("/usr/local/bin/chromedriver")
    driver.get("https://www.flashscorekz.com/basketball/")
    # driver.get("https://www.flashscorekz.com/hockey/")
    sport_id = 1
    status = "завершенные"
    top_header_data = {}
    driver.implicitly_wait(10)
    # жмем на кнопку принять куки.
    try:
        driver.find_element("id", 'onetrust-accept-btn-handler').click()
    except Exception as e:
        print("accept_all_button exception ", e)
    tabs = driver.find_elements("xpath", "//div[@class='filters__text filters__text--default']")
    for tab in tabs:
        tab_name = tab.text
        if tab_name.lower() == "завершенные":
            tab.click()
            driver.implicitly_wait(10)

    # получаем хедеры
    try:
        top_headers_list = driver.find_elements("xpath", "//div[@class='event__header top']")
        event_header_list = driver.find_elements("xpath", "//div[@class='event__header']")
        header_list = top_headers_list + event_header_list
        # top_headers_list = driver.find_elements("xpath", "//div[@class='event__titleBox']")
        for header in header_list:
            # проверяем есть ли у топ хедера сохраненная лига и команды
            country_name = header.find_element(By.CLASS_NAME, "event__title--type")
            league_name_el = header.find_element(By.CLASS_NAME, "event__title--name")
            country = country_name.text.lower()
            league_name = league_name_el.text

            # проверяем есть ли эта лига в базе
            league_data = LeagueDB.query.filter_by(league_country=country, league_name=league_name).first()
            if league_data:
                print(f"Данные о лиге уже есть в базе. Страна: ", country, ". Лига: ", league_name)
            else:
                # создаем новую лигу
                print(f"Данных о лиге {league_name} нет в базе")
                new_league = LeagueDB(
                    league_country=country,
                    league_name=league_name,
                    sport_id=sport_id
                )
                db.session.add(new_league)
                db.session.commit()
                league_data = LeagueDB.query.order_by(desc(LeagueDB.league_id)).first()
                league_id = league_data.league_id
                print("Лига : ", league_data.league_name, " была создана")
                # переходим в каталог команд
                # вот этот переход наверное нужно сделать в другом драйвере
                # input("должен открыться")
                driver_2 = webdriver.Chrome("/usr/local/bin/chromedriver")
                driver_2.get("https://www.flashscorekz.com/basketball/")
                driver_2.implicitly_wait(10)
                # жмем на кнопку принять куки.
                try:
                    driver_2.find_element("id", 'onetrust-accept-btn-handler').click()
                except Exception as e:
                    print("accept_all_button exception ", e)
                tabs = driver_2.find_elements("xpath", "//div[@class='filters__text filters__text--default']")
                for tab in tabs:
                    tab_name = tab.text
                    if tab_name.lower() == "завершенные":
                        tab.click()
                        driver.implicitly_wait(10)
                        #  здесь мы должны оказаться во вкладке Завершенные
                        # В драйвере 2 итерируемся по блокам и ищем тот, где есть наша лига, которую нужно заполнить командами
                        top_headers_list = driver_2.find_elements("xpath", "//div[@class='event__header top']")
                        event_header_list = driver_2.find_elements("xpath", "//div[@class='event__header']")
                        header_list_2 = top_headers_list + event_header_list
                        # top_headers_list = driver.find_elements("xpath", "//div[@class='event__titleBox']")
                        for header_2 in header_list_2:
                            # проверяем есть ли у топ хедера сохраненная лига и команды
                            country_name = header_2.find_element(By.CLASS_NAME, "event__title--type")
                            league_name_el_driver_2 = header_2.find_element(By.CLASS_NAME, "event__title--name")
                            country_driver_2 = country_name.text.lower()
                            league_name_driver_2 = league_name_el.text
                            print("country_driver_2: ", country_driver_2, ", league_name_driver_2: ", league_name_driver_2)
                            if country_driver_2 == country and league_name_driver_2 == league_name:
                                league_name_el_driver_2 .click()
                                driver_2.implicitly_wait(3)
                                driver_2.find_element("xpath", "//a[@class='tabs__tab standings_table']").click()
                                driver_2.implicitly_wait(10)

project/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
{% block head %}
    <meta charset="UTF-8">


    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/css/bootstrap.css">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.24/css/jquery.dataTables.css">


{% endblock %}
<title>{% block title %}  {% endblock %}</title>
</head>
<body>
<!-- Это начало Nav Bar-->
  <!-- https://getbootstrap.com/docs/4.0/examples/pricing/# -->

    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
      <h5 class="my-0 mr-md-auto font-weight-normal">Fights Management System</h5>
      <nav class="my-2 my-md-0 mr-md-3">
        <a class="p-2 text-dark" href="{{url_for('home.competitions')}}">Соревнования</a>
        <a class="p-2 text-dark" href="{{url_for('home.participants')}}">Спортсмены</a>
      </nav>
    </div>

<!-- Это конец Nav Bar-->

    <div id="content">
        {% block content %}

        {% endblock %}
    </div> <!-- Это конец блока Content-->

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
<script>
    $(document).ready(function () {
        $('.navbar-nav li').on('click', function(){

            $('.navbar-nav li').removeClass('active');
            $(this).addClass('active');
  });
    })
</script>

</body>
</html>

project/templates/home.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/css/bootstrap-select.min.css">


   <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <style>
     a:hover {
      cursor:pointer;
     }

        body, html {
            font-family: Arial;
            font-size: 11pt;
            padding: 0;
            margin: 0;
            width: 100%;
            height: 95%;
            background-color: white;
        }
        p {
            padding: 10px;
        }
        #map {
            width: 100%;
            height: 90%;
        }
    </style>
    <title>Home</title>
</head>
<body>


<!--<div class="container-fluid" style="margin-top: 10px">-->
<div class="container" style="margin-top: 10px">
    <div class="row">
        <div class="col">
            <h3>Парсинг www.flashscorekz.com</h3>
<!--            <a href="https://www.flashscorekz.com/basketball/"  target="_blank" class="btn btn-info" role="button">Начать парсинг</a>-->

            <a href="{{url_for('home.parse_live')}}"><button type="button" class="btn btn-info">Live</button></a>

            <a href="{{url_for('home.parse_finished')}}"><button type="button" class="btn btn-info">Завершенные</button></a>
        </div>

    </div>


    <div class="row" style="margin-top: 10px">
        <div class="col">
            <ul class="nav nav-tabs">
                    <li class="nav-item"><a class="nav-link" href="#live_matches" data-toggle="tab">Live</a></li>

                    <li class="nav-item"><a class="nav-link" href="#settings" data-toggle="tab">Настройки</a></li>
                </ul>

                <div class="tab-content" id="tabs">
                    <div class="tab-pane" id="live_matches">

                    </div>
                    <div class="tab-pane" id="settings">
                         <div class="row">
                            <div class="col">
                                <form method="POST" action="{{ url_for('home.parse_league')}}">
                                  <div class="form-group">
                                    <label for="exampleInputEmail1">link</label>
                                    <input type="text" class="form-control" id="exampleInputEmail1" placeholder="Enter link" name="link" required>
                                    <small id="emailHelp" class="form-text text-muted">ссылка на страницу с командами лиги для парсинга в справочник.</small>
                                  </div>
                                  <div class="form-group">
                                    <label for="exampleInputPassword1">Спорт</label>
                                    <input type="text" class="form-control" id="exampleInputPassword1" placeholder="Спорт" name="sport" required>
                                  </div>

                                  <button type="submit" class="btn btn-primary">Submit</button>
                                </form>
                            </div>
                        </div>

                    </div>
                </div>

        </div>
    </div>

    <div class="row">
        <div class="col">
            <div class="live_matches">

            </div>
        </div>
    </div>


</div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/js/bootstrap-select.min.js"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/3.0.4/socket.io.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.5.0/Chart.js"></script>
<!--<script src="https://api-maps.yandex.ru/2.0-stable/?apikey=cd0bfb13-727e-4fa7-8462-43cb4d380772&load=package.standard&lang=ru-RU" type="text/javascript"></script>-->

<script type="text/javascript">
    data_dict = {{ data | tojson }}
    $(document).ready(function(){
        var active_tab = data_dict['active_tab_pass'];

        activaTab(active_tab);
        console.log('active_tab: ', active_tab)
        function activaTab(tab){
          $('.nav-tabs a[href="#' + tab + '"]').tab('show');
        };

        $.ajax({
                 url: '/live_mathes_page_load_ajaxfile',
                 type: 'post',
                 success: function(data){

                     $('.live_matches').html(data);
                     $('.live_matches').append(data.htmlresponse);

                }
             });
    })


</script>



</body>
</html>

project/templates/live_matches.html
<!DOCTYPE html>
<html lang="ru">
<head>
	<meta charset="UTF-8">
	<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/css/bootstrap.css">
	<title>
		OH
	</title>
	<style>
	.chart-container {
	  position: relative;
	  margin: auto;
	  height: 80vh;
	  width: 80vw;
	}
</style>
</head>
<body>

<div style="margin-top: 15px">
	{% for live_matche_data in live_matches_data %}
  <h3>{{ live_matche_data.sport_name.capitalize() }}</h3>
  <h5>{{ live_matche_data.league_country.upper() }}: {{ live_matche_data.league_name }} </h5>

	<div class="row">
		<div class="col">
			<table class="table">
				<thead>
				  <tr>
					<th scope="col">Статус матча</th>
					<th scope="col">Команды</th>
					<th scope="col">Матч</th>
					<th scope="col">1</th>
					<th scope="col">2</th>
					<th scope="col">3</th>
					<th scope="col">4</th>
				  </tr>
				</thead>
				<tbody>
					<tr>
						<td rowspan="2">
							{{ live_matche_data.match_status_name }}
						</td>
						<td>
							{{ live_matche_data.match_home_team_name }}
						</td>
						<td>
							{{ live_matche_data.home_team_final_score }}
						</td>
						<td>

						</td>
						<td>

						</td>
						<td>

						</td>
						<td>

						</td>
					</tr>
					<tr>
<!--						<td>-->
<!--							{{ live_matche_data.match_status_name }}-->
<!--						</td>-->
						<td>
							{{ live_matche_data.match_away_team_name }}
						</td>
						<td>
						{{ live_matche_data.away_team_final_score }}
						</td>
						<td>

						</td>
						<td>

						</td>
						<td>

						</td>
						<td>

						</td>
					</tr>
				</tbody>
			</table>


		</div>
		<div class="col">
			<div class="chart-container" style="position: relative; height:17vh; width:40vw">
				<canvas id="myChart"></canvas>
			</div>
		</div>
	</div>
	{% endfor %}
</div>

<!--	<canvas id="myChart" width="400" height="100"></canvas>-->
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.5.0/Chart.js"></script>
 <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js" defer></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js"></script>

<script>
var ctx = document.getElementById('myChart').getContext('2d');
  var myChart = new Chart(ctx, {
    type: 'bar',
    data: {
      labels: ['Red', 'Blue', 'Yellow', 'Green', 'Purple', 'Orange'],
      datasets: [{
        label: '# of Votes',
        data: [12, 19, 3, 5, 2, 3],
        backgroundColor: [
          'rgba(255, 99, 132, 0.2)',
          'rgba(54, 162, 235, 0.2)',
          'rgba(255, 206, 86, 0.2)',
          'rgba(75, 192, 192, 0.2)',
          'rgba(153, 102, 255, 0.2)',
          'rgba(255, 159, 64, 0.2)'
        ],
        borderColor: [
          'rgba(255, 99, 132, 1)',
          'rgba(54, 162, 235, 1)',
          'rgba(255, 206, 86, 1)',
          'rgba(75, 192, 192, 1)',
          'rgba(153, 102, 255, 1)',
          'rgba(255, 159, 64, 1)'
        ],
        borderWidth: 1
      }]
    },
    options: {
      scales: {
        y: {
          beginAtZero: true
        }
      }
    }
  });

	</script>
</body>
</html>











<!--<div style="margin-top: 15px">-->
<!--  <h3>Баскетбол</h3>-->
<!--  <h5>ЕВРОПА: Евролига</h5>-->
<!--  <div class="row">-->
<!--    <div class="col">-->
<!--      <table class="table">-->
<!--        <thead>-->
<!--          <tr>-->
<!--            <th scope="col">Статус матча</th>-->
<!--            <th scope="col">Команды</th>-->
<!--            <th scope="col">Матч</th>-->
<!--            <th scope="col">1-й период</th>-->
<!--            <th scope="col">2-й период</th>-->
<!--            <th scope="col">3-й период</th>-->
<!--            <th scope="col">4-й период</th>-->
<!--          </tr>-->
<!--        </thead>-->
<!--        <tbody>-->
<!--          <tr>-->
<!--            <td rowspan="2" style="vertical-align: middle;">3-я четверть</td>-->
<!--            <td>GOTOBELES Astana</td>-->
<!--            <td>50</td>-->
<!--            <td>19</td>-->
<!--            <td></td>-->
<!--            <td></td>-->
<!--            <td></td>-->
<!--          </tr>-->
<!--          <tr>-->
<!--            <td>БИИК Шымкент</td>-->
<!--            <td>63</td>-->
<!--            <td>20</td>-->
<!--            <td></td>-->
<!--            <td></td>-->
<!--            <td></td>-->
<!--          </tr>-->

<!--        </tbody>-->
<!--      </table>-->
<!--      </div>-->
<!--    <div class="col">-->
<!--      здесь должен быть график-->
<!--      <canvas id="myChart" width="400" height="400"></canvas>-->
<!--    </div>-->
<!--</div>-->
<!--<hr>-->


<!--&lt;!&ndash;<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.9.1/chart.min.js"></script>&ndash;&gt;-->
<!--<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.5.0/Chart.js"></script>-->
<!--&lt;!&ndash;<script type="text/javascript" src="http://www.chartjs.org/assets/Chart.js"></script>&ndash;&gt;-->
<!--<script>-->
<!--$(document).ready(function() {-->
<!--  var ctx = document.getElementById('myChart').getContext('2d');-->
<!--  var myChart = Chart(ctx, {-->
<!--    type: 'bar',-->
<!--    data: {-->
<!--      labels: ['Red', 'Blue', 'Yellow', 'Green', 'Purple', 'Orange'],-->
<!--      datasets: [{-->
<!--        label: '# of Votes',-->
<!--        data: [12, 19, 3, 5, 2, 3],-->
<!--        backgroundColor: [-->
<!--          'rgba(255, 99, 132, 0.2)',-->
<!--          'rgba(54, 162, 235, 0.2)',-->
<!--          'rgba(255, 206, 86, 0.2)',-->
<!--          'rgba(75, 192, 192, 0.2)',-->
<!--          'rgba(153, 102, 255, 0.2)',-->
<!--          'rgba(255, 159, 64, 0.2)'-->
<!--        ],-->
<!--        borderColor: [-->
<!--          'rgba(255, 99, 132, 1)',-->
<!--          'rgba(54, 162, 235, 1)',-->
<!--          'rgba(255, 206, 86, 1)',-->
<!--          'rgba(75, 192, 192, 1)',-->
<!--          'rgba(153, 102, 255, 1)',-->
<!--          'rgba(255, 159, 64, 1)'-->
<!--        ],-->
<!--        borderWidth: 1-->
<!--      }]-->
<!--    },-->
<!--    options: {-->
<!--      scales: {-->
<!--        y: {-->
<!--          beginAtZero: true-->
<!--        }-->
<!--      }-->
<!--    }-->
<!--  });-->
<!--})-->
<!--</script>-->
<!--</div>-->